FROM mysql:8.0

# Variables de entorno para MySQL
ENV MYSQL_ROOT_PASSWORD=passwordRoot
ENV MYSQL_DATABASE=mydatabase
ENV MYSQL_USER=monolithicDocker
ENV MYSQL_PASSWORD=monolithicDocker

# Exponer el puerto de MySQL
EXPOSE 3306